Update patch set 7
Patch Set 7:

> Patch Set 6: Code-Review-1
> 
> Doesn't work on python 3.6 on RHEL 8
> 
> TypeError: a bytes-like object is required, not 'str'
> 
> skopeo version 1.0.0

Fixed in next patchset, yaml.dump() expects a filedescriptor open in text mode.

Patch-set: 7