Update patch set 7
Patch Set 7: Code-Review+1

Almost perfect for me.
I think we should catch the subprocess.CalledProcessError when the registry is not running and display something like:

"Are you sure <RegistryName> is up and running ?" instead of 

```
  File "/usr/lib/python3.6/site-packages/dci_downloader/containers.py", line 67, in skopeo_sync
    raise CalledProcessError(retcode, " ".join(skopeo_sync_command))
subprocess.CalledProcessError: Command 'skopeo sync --src yaml --dest docker --dest-tls-verify=false --dest-no-creds /tmp/tmpt7l19tpr localhost:5000' returned non-zero exit status 1.
```

Patch-set: 7
Reviewer: Gerrit User 405 <405@6c1dc8ef-8b94-40e4-bd83-c2359d45ecc0>
Label: Code-Review=+1