Update patch set 6
Patch Set 6: Code-Review-1

Doesn't work on python 3.6 on RHEL 8

TypeError: a bytes-like object is required, not 'str'

skopeo version 1.0.0

Patch-set: 6
Reviewer: Gerrit User 405 <405@6c1dc8ef-8b94-40e4-bd83-c2359d45ecc0>
Label: Code-Review=-1